- project:
    name: openstack/ansible-role-k8s-mariadb
    check:
      jobs:
        - ansible-role-k8s-mariadb-kubernetes-centos
        - ansible-role-k8s-mariadb-openshift-centos

- nodeset:
    name: ansible-role-k8s-centos
    nodes:
      - name: primary
        label: centos-7

- job:
    name: ansible-role-k8s-base
    pre-run: tests/pre.yml
    run: tests/run.yml
    post-run: tests/post.yml
    attempts: 1
    timeout: 10800
    required-projects:
      - openstack/ansible-role-k8s-tripleo

- job:
    name: ansible-role-k8s-mariadb-kubernetes-centos
    parent: ansible-role-k8s-base
    nodeset: ansible-role-k8s-centos
    vars:
      coe: kubernetes
      project_name: ansible-role-k8s-mariadb
    required-projects:
      - openstack/ansible-role-k8s-mariadb

- job:
    name: ansible-role-k8s-mariadb-openshift-centos
    parent: ansible-role-k8s-base
    nodeset: ansible-role-k8s-centos
    vars:
      coe: openshift
      project_name: ansible-role-k8s-mariadb
    required-projects:
      - openstack/ansible-role-k8s-mariadb
