- name: Translate hieradata
  include_role:
    name: 'ansible-role-k8s-tripleo'
  vars:
    hieradata: '{{hiera_data}}'
    hieradata_file: '{{hiera_data_file}}'
    schema:
      tripleo::profile::base::database::mysql::bind_address: bind_address
      tripleo::profile::base::database::mysql::mysql_server_options: mysql_server_options
      mysql::server::root_password: root_password
      mysql_clustercheck_password: clustercheck_password
      mysql_max_connections: mysql_max_connections
    fact_variable: 'mariadb_config'

- debug:
    var: mariadb_config
    verbosity: 2
