- name: Translate hieradata
  parse_tripleo_hiera:
    hieradata_file: '{{ hieradata_file }}'
    hieradata: '{{ hieradata }}'
    schema:
      tripleo::profile::base::database::mysql::bind_address: bind_address
      tripleo::profile::base::database::mysql::mysql_server_options: mysql_server_options
      mysql::server::root_password: root_password
      mysql_clustercheck_password: clustercheck_password
      mysql_max_connections: mysql_max_connections
    default: '{{mariadb_config}}'
  when:
    - hieradata or hieradata_file
    - schema
  register: result

- name: Set facts
  set_fact:
    mariadb_config: '{{result.conf_dict}}'
  when:
    - result.conf_dict is defined
    - fact_variable != ''

- debug:
    var: mariadb_config
    verbosity: 2
